// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3f-5-fR0RKuSbLxV8jqo_uRHTXwsmJH0',
    appId: '1:94591898306:web:4244c6e522d117d6fd215b',
    messagingSenderId: '94591898306',
    projectId: 'example-project-c6215',
    authDomain: 'example-project-c6215.firebaseapp.com',
    storageBucket: 'example-project-c6215.firebasestorage.app',
    measurementId: 'G-C81XL02FXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD2cauFz_CJnbJnmNnGXfcQoXs5qENrFI',
    appId: '1:94591898306:android:c84d2d4358cb5446fd215b',
    messagingSenderId: '94591898306',
    projectId: 'example-project-c6215',
    storageBucket: 'example-project-c6215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABluGOjMthHW3BWWWRITivjHjsw7ksHCs',
    appId: '1:94591898306:ios:10f658b6a742c967fd215b',
    messagingSenderId: '94591898306',
    projectId: 'example-project-c6215',
    storageBucket: 'example-project-c6215.firebasestorage.app',
    iosBundleId: 'com.example.firstProgrammingAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABluGOjMthHW3BWWWRITivjHjsw7ksHCs',
    appId: '1:94591898306:ios:10f658b6a742c967fd215b',
    messagingSenderId: '94591898306',
    projectId: 'example-project-c6215',
    storageBucket: 'example-project-c6215.firebasestorage.app',
    iosBundleId: 'com.example.firstProgrammingAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3f-5-fR0RKuSbLxV8jqo_uRHTXwsmJH0',
    appId: '1:94591898306:web:1a43898503514624fd215b',
    messagingSenderId: '94591898306',
    projectId: 'example-project-c6215',
    authDomain: 'example-project-c6215.firebaseapp.com',
    storageBucket: 'example-project-c6215.firebasestorage.app',
    measurementId: 'G-SM5K1XPCST',
  );

}